version: "3"

services:
  node:
    build: .
    user: node
    container_name: blogs_api
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: ${NODE_ENV}
      API_PORT: ${API_PORT}
      DB_DIALECT: ${DB_DIALECT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
  db:
    container_name: blogs_api_db
    image: mysql:8.0.21
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

networks:
  default:
    name: blogs_api_net
